apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: explorer-app
  labels:
     run: explorer-app
spec:
  selector:
    matchLabels:
      run: explorer-app
  replicas: 1
  template:
    metadata:
      labels:
        run: explorer-app
    spec:
      containers:
      - name: postgres-db
        image: hyperledger/explorer
        command: ["sh" , "-c" , "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"]
        env:
        - name: DATABASE_HOST
          value: explorer-db
        - name: DATABASE_USERNAME
          value: "username"
        - name: DATABASE_PASSWORD
          value: "password"

        volumeMounts:
        - name: my-pvc-nfs
          mountPath: /opt/explorer/app/platform/fabric/config.json
          subPath: explorer/config.json
        - name: my-pvc-nfs
          mountPath: /opt/explorer/app/platform/fabric/connection-profile
          subPath: explorer/connection-profile
        - name: my-pvc-nfs
          mountPath: /tmp/crypto
          subPath: crypto-config
#        - name: my-pvc-nfs
#          mountPath: /opt/wallet
#          subPath: explorer/walletstore

      volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: explorer-app
  labels:
    run: explorer-app
spec:
  selector:
    run: explorer-app
  ports:
    - name: explorer-app
      port: 8080
    
  type: ClusterIP 